<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# Non-Asset-Market Index{#non-index}

## Data

In the empirical exercise I use uncertainty indexes from distinct sources for the USA economy. Specifically, the index are:

- The Economic Policy Uncertainty Index (EPU) developed by @Baker_2016. This Index is available from January 1985 through September 2019 in the authors website [@bakebloodavi:2019]. 
- The Monetary Policy Uncertainty Index (MPU) developed by @Baker_2016; henceforth BBD U.S. MPU. This Index is available from January 1985 through September 2019 in the authors website [@bakebloodavi:2019]. Likewise, the authors construct two variants  of them monthly MPU Index for the United States by using two different sets of newspapers.
- The Monetary Policy Uncertainty Index (MPU) developed by 

## Non-Asset-Market Uncertainty Index

```{r}
source("./R/Import_Uncertainty.R")
```




<!-- \clearpage -->


<!-- # ```{r maxdelays, results="asis"} -->
<!-- # kable(max_delays,  -->
<!-- #       col.names = c("Airline", "Max Arrival Delay"), -->
<!-- #       caption = "Maximum Delays by Airline", -->
<!-- #       caption.short = "Max Delays by Airline", -->
<!-- #       longtable = TRUE, -->
<!-- #       booktabs = TRUE) -->
<!-- # ``` -->
