# Literature {#literature}

In this chapter I review the role of risk and uncertainty in [Risk and Uncertainty]. Then, I documented the history of index construction in macroeconomics in [History of indices construction]. Finally, I show the main uncertainty indices in the field---which use some of the methodologies exposed in the previous subsection---in [Empirical Measures of Uncertainty].

<!-- ## lag order raw -->

<!-- - @kilian:1998 -->

<!-- ## fixed lag -->



## Risk and Uncertainty {#risk-and-uncertainty}

First of all, the uncertainty has been put inside a framework of irreversible investment, i.e., for future investment opportunities is cautious to wait until the uncertainty levels have passed. Therefore, aggregate uncertainty shocks affect investments, labor and in general reducing the real activity [@bernanke:1983]. Moreover, @romer:1990 showed that consumers postpone their acquisition of durable goods in periods of high uncertainty. In addition, @bansyaro:2004 declares that the uncertainty results in reduction of equity prices through the reduction of long-run growth in the economy.

@bekahoerduca:2013 study the relationship between uncertainty and policy interventions. The authors concludes that uncertainty has an important role in the transmission of monetary policy mechanisms. This marks the question if facing uncertainty requires considerable policy action or not.

## History of Indices Construction {#history-of-indices-construction}

The DFM allows to resolve a classic problem in empirical macroeconomics, that is, the construction of an index of indicators of economic activity. In the DFM framework, the latent factor summarizes the comovements of the observed variables. Hence, the estimate of a latent factor from a single DFM is an index of the movements of the relevant series.

The first application of DFMs for monitoring the economy was the @stocwats:1991 experimental coincident index (XCI), which was active between May 1989 to December 2003. This index was the result from the Kalman filter estimate of one single factor among four monthly coincident indices: total nonfarm employment, the index of industrial production, real manufacturing and trade sales, and real personal income less transfers. @stocwats:1993 shown that in retrospective analysis,the XCI was successful in contemporaneous monitoring and in real-time detection of the recession of 1990 although only less that six months before the recession.

After the start of using DFMs for index construction were estimated subsequent indices through state-space models. First, monthly real activity indices for US states [@cronclay:2005]---that are active from 2005. Second, the inclusion of mixed-frequency series to the XCI in @marimura:2003. Third, @aruodiebscot:2009 developed a mixed-frequency index for economic conditions so-called ADS. In contrast, recent studies has focused in large dimensional systems. @stocwats:1999 constructed the base for the Chicago Fed National Activity Index (CFNAI), that is the principal components estimate of the common factor in 85 real activity variables. Finally, an European Union real economy activity index---named EuroCOIN---based on 145 Euro-area real activity variables was developed by @alticrisfornlippvero:2010.

## Empirical Measures of Uncertainty {#empirical-measures-of-uncertainty}

Different measures of uncertainty and proxies of this have being proposed in the literature. Nevertheless, the classification used to describe these indices in this document will be the underlying outcome, i.e., asset price or macroeconomic variable. Hence, the allegedly uncertainty measures are divided as non-asset-market and asset-market. In this document are considered the non-asset-market measures because these are the base for the index proposed^[This decision left out studies based on microeconomic information such as the cross-sectional dispersion of ﬁrms’ proﬁts [@bloom:2009] and estimated time-varying productivity [@bloofloejaimsapoterr:2018.]].

The first indicator in this category is the economic policy uncertainty index developed by @bakebloodavi:2016 which is based on three underlying components: news-coverage about policy-related economic uncertainty, tax expiration code data and economic forecaster disagreement. The first component is an index of search results from 10 major U.S. newspapers for articles that contain terms related to economic and policy uncertainty. The second component gauges uncertainty regarding the federal tax code---through reports from the Congressional Budget Office (CBO)---by counting the number of federal tax code provisions set to expire in future years. The third component relies on disagreement between professional forecasters---through the Federal Reserve Bank of Philadelphia's Survey of Professional Forecasters---as an indicator of uncertainty. Moreover, the authors have developed a new economic policy uncertainty index based on newspaper archives from Access World New's NewsBank service which contains the archives of thousands of newspapers from across the globe. Finally, the authors also have a subindice for monetary policy---for each source, that is, one index draw from a balanced panel of 10 major national and regional U.S. newspapers and the other one from hundreds of U.S. newspapers covered by Access World News---that contains additional terms relevant to monetary policy.

In the same vein as last authors it is the monetary policy uncertainty index from @hustrogesun:2019. This newspaper-based index search for keywords related to monetary policy uncertainty---related to the United States---in the New York Times, Wall Street Journal and Washington Post. Then, scale the count by the total number of news articles mentioning the Federal Reserve for each newspaper in a given period. In short, the index measures the perceived uncertainty surrounding the Federal Reserve Board's policy decisions and their consequences.

On the other hand, @caldiaco:2018 proposed a geopolitical risk index counting the occurrence of words related to geopolitical tensions in eleven leading international newspapers. In other words, the index measures the risk associated with events that affect the normal course of domestic politics and international relations. The authors also have proposed two indices more for distinguish geopolitical acts and geopolitical threats.

@scotti:2016 uses macroeconomic news and survey forecast to construct a measure of uncertainty about the state of the economy. The author's macroeconomic uncertainty index is based on a weighted average of economic data surprises, where the latter are the difference between consensus expectations and economic data releases.

Lastly, @juraludvng:2015 and @ludvmang:2015 developed a macroeconomic, financial and real uncertainty index of uncertainty. These measures are based on removing the forecastable component of the series. In brief, the uncertainty can be constructed as an weighted average of the forecast error variance of hundreds of economic series.
