---
author: "Juan Felipe Padilla Sepúlveda"
date: "`r format(Sys.time(), '%B %Y')`"
institution: "Universidad del Valle"
division: "Social and Economic Sciences"
advisor: "Jorge Mario Uribe Gil"
department: "Faculty of Economics"
degree: "Bachelor of Economics"
title: "Non-Asset-Market Uncertainty"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: thesisdown::thesis_pdf
abstract: |
  `r paste(readLines("00-Abstract.Rmd"), collapse = "\n  ")`
bibliography: [bib/thesis.bib]
link-citations: yes
colorlinks: yes
csl: [csl/apa.csl]
lot: true
lof: true
header-includes:
   - \usepackage{booktabs}
   - \usepackage{longtable}
   - \usepackage{array}
   - \usepackage{multirow}
   - \usepackage{wrapfig}
   - \usepackage{float}
   - \usepackage{colortbl}
   - \usepackage{pdflscape}
   - \usepackage{tabu}
   - \usepackage{threeparttable}
   - \usepackage{threeparttablex}
   - \usepackage[normalem]{ulem}
   - \usepackage{makecell}
   - \usepackage{xcolor}
   - \usepackage{caption}
   - \captionsetup[figure]{font=small}
   - \captionsetup[table]{font=small}
   - \DeclareMathOperator{\diag}{diag}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  fig.align = "center",
  fig.asp = 0.618,
  fig.show = "hold",
  fig.width = 6,
  out.width = "70%",
  tidy = "styler"
)

# R packages

if (!require(pacman)) install.packages("pacman")

library(pacman)

p_load(corrplot)
p_load_gh("rbagd/dynfactoR")
p_load(forcats)
p_load(ggthemes)
p_load_gh("ChandlerLutz/ggts")
p_load(here)
p_load(kableExtra)
p_load(knitr)
p_load(magrittr)
p_load(psych)
p_load(readr)
p_load(stringr)
p_load_gh("ismayc/thesisdown")
p_load(tidymodels)
p_load(tidyquant)
p_load(tidyr)
p_load(vars)
p_load(viridis)

# Global options

# Set seed of random number generator
set.seed(1112494378)

# Set theme of ggplot
theme_set(theme_tufte())

# Declare preferences
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("VAR", "vars")
conflicted::conflict_prefer("here", "here")
conflicted::conflict_prefer("lag", "dplyr")
```

```{bash xlsx2csv, eval = FALSE}
# Transform uncertainty indexes from .xlsx to .csv

Rscript ./R/xlsx2csv.R
```

```{bash API2csv, eval = FALSE}
# Import series through FED, Yahoo Finance and Quandl API

Rscript ./R/API2csv.R
```

```{r comma}
comma <- function(x) format(x, digits = 2, big.mark = ",")
```

# Introduction {.unnumbered}

Uncertainty has been a very important issue in economic theory, especially since it is considered a different concept of risk knight15, because agents are always exposed to scenarios of uncertainty (\ cite {greenspan04} ). Therefore, it is necessary to measure market uncertainty to analyze the effects of its changes in economic activity.
